"""Tests for the self-knowledge generator (story-64 Phase B). Pure — stdlib, no DB/network."""

import importlib.util
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
_spec = importlib.util.spec_from_file_location(
    "build_agent_self_knowledge", REPO / "scripts" / "build_agent_self_knowledge.py")
gen = importlib.util.module_from_spec(_spec)
sys.modules["build_agent_self_knowledge"] = gen
_spec.loader.exec_module(gen)


SRC = """---
minimum_authority: admin
status: active
---

# Self-Knowledge Sources

## Output

- `knowledge/about-myself/generated/self-knowledge.md`

## Sources

### knowledge/about-myself/capabilities.md

Reason: Reviewed identity.

Sections:
- What I Am
"""


def test_parse_sources_ok():
    out, sources = gen.parse_sources(SRC)
    assert out == "knowledge/about-myself/generated/self-knowledge.md"
    assert sources[0]["path"] == "knowledge/about-myself/capabilities.md"
    assert sources[0]["sections"] == ["What I Am"]


@pytest.mark.parametrize("bad", [
    SRC.replace("## Output\n\n- `knowledge/about-myself/generated/self-knowledge.md`\n", "## Output\n"),
    SRC.replace("Reason: Reviewed identity.\n", ""),          # missing reason
    SRC.replace("Sections:\n- What I Am\n", ""),              # no sections
])
def test_parse_sources_rejects(bad):
    with pytest.raises(gen.GeneratorError):
        gen.parse_sources(bad)


def test_extract_section_body_and_stops_at_next_heading():
    doc = "# A\n\nalpha body\n\n## A1\n\nnested\n\n# B\n\nbeta"
    assert gen.extract_section(doc, "A") == "alpha body\n\n## A1\n\nnested"
    assert gen.extract_section(doc, "B") == "beta"


def test_extract_section_missing_raises():
    with pytest.raises(gen.GeneratorError):
        gen.extract_section("# X\n\nbody", "Nope")


def test_extract_section_empty_raises():
    with pytest.raises(gen.GeneratorError):
        gen.extract_section("# X\n\n# Y\n\nbody", "X")


def test_validate_source_path_blocks_denylist_and_traversal():
    for bad in ["../x.md", "/etc/passwd", "admin_api/config.yaml", "knowledge/../.env", "a\\b.md"]:
        with pytest.raises(gen.GeneratorError):
            gen._validate_source_path(bad)


def test_render_scans_secrets(tmp_path, monkeypatch):
    # a source whose section body carries a secret must be rejected
    src = tmp_path / "s.md"
    src.write_text("# Cap\n\ntoken sk-abcdefghijklmnopqrstuvwxyz012345\n")
    monkeypatch.setattr(gen, "REPO_ROOT", tmp_path)
    with pytest.raises(gen.GeneratorError):
        gen.render([{"path": "s.md", "reason": "r", "sections": ["Cap"]}])


def test_generate_is_deterministic_against_repo_sources():
    # the committed sources build without error and are byte-identical across two renders
    out1, content1 = gen.build()
    out2, content2 = gen.build()
    assert content1 == content2
    assert content1.startswith("---\nminimum_authority: admin\nstatus: active\n---")
    assert "GENERATED by" in content1


def test_committed_output_is_not_stale():
    # `check` must pass on the committed generated file (guards drift)
    assert gen.cmd_check() == 0
