#!/usr/bin/env python3
"""Deterministic self-knowledge generator (story-64 Phase B).

Assembles an authority-filtered self-knowledge document from allowlisted source-doc sections listed in
`knowledge/about-myself/sources.md`. Pure standard library; no LLM, no network. Two commands:

    python3 scripts/build_agent_self_knowledge.py generate   # write the output file
    python3 scripts/build_agent_self_knowledge.py check       # nonzero if missing/stale

The output is `minimum_authority: admin` — the runtime discloses it only to admin/super_admin; other
approved people receive a separate public capability summary (Phase C). Secrets are excluded at every
step: source paths are validated against a denylist, and both extracts and final output are scanned.

Never hand-edit the generated file. Edit the sources or the source list, regenerate, review the diff,
then run `check`.
"""

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCES_FILE = REPO_ROOT / "knowledge" / "about-myself" / "sources.md"

# Source paths that may contain secrets/runtime state — never extract from these.
DENY_SUBSTRINGS = [
    ".env", "config.yaml", "relay.env", "auth.json", "auth.lock",
    "/.hermes/", "profiles/", "sessions/", "audit", "snapshots",
    "INFRASTRUCTURE", "secret", "token", "credential",
]

SECRET_PATTERNS = [
    re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----"),
    re.compile(r"\bsk-[A-Za-z0-9]{20,}\b"),
    re.compile(r"\bAKIA[0-9A-Z]{16}\b"),
    re.compile(r"\bghp_[A-Za-z0-9]{20,}\b"),
    re.compile(r"\bxox[baprs]-[A-Za-z0-9-]{10,}\b"),
]

GENERATED_NOTICE = (
    "<!-- GENERATED by scripts/build_agent_self_knowledge.py — do not hand-edit. "
    "Edit the sources or knowledge/about-myself/sources.md, then regenerate. -->"
)
DISCLOSURE_POLICY = (
    "Disclosure: this document is admin-level. Share high-level capability information broadly, but "
    "reserve operational setup and administrative detail for administrators. Never disclose secrets, "
    "credentials, tokens, or infrastructure specifics at any authority level."
)
REVIEWED_SUMMARY = (
    "I am James, SimplifyOps's operational AI agent. I converse with approved people, draw on curated "
    "knowledge and long-term memory, and use governed tools scoped to each requester's authority. "
    "Every message passes governance before I act, and I have no hidden path around those checks."
)


class GeneratorError(ValueError):
    """A malformed source list, missing source/section, or blocked/secret-bearing input."""


def _scan_secrets(text: str, where: str) -> None:
    if any(p.search(text) for p in SECRET_PATTERNS):
        raise GeneratorError(f"secret-like material detected in {where}")


def _validate_source_path(rel: str) -> Path:
    if rel != rel.strip() or rel.startswith("/") or "\\" in rel or ".." in rel.split("/"):
        raise GeneratorError(f"invalid or unsafe source path: {rel!r}")
    low = rel.lower()
    if any(bad in low for bad in DENY_SUBSTRINGS):
        raise GeneratorError(f"source path is on the secret/runtime denylist: {rel!r}")
    path = (REPO_ROOT / rel).resolve()
    if REPO_ROOT not in path.parents:
        raise GeneratorError(f"source path escapes the repository: {rel!r}")
    if not path.exists():
        raise GeneratorError(f"source file not found: {rel}")
    return path


def parse_sources(text: str) -> tuple[str, list[dict]]:
    """Parse sources.md → (output_path, [{path, reason, sections:[...]}, ...]). Raises on malformed."""
    # strip front matter if present
    m = re.match(r"^---\s*\n.*?\n---\s*\n(.*)$", text, re.DOTALL)
    body = m.group(1) if m else text

    out_m = re.search(r"##\s+Output\s*\n(.*?)(?=\n##\s|\Z)", body, re.DOTALL)
    if not out_m:
        raise GeneratorError("sources.md missing '## Output' section")
    out_paths = re.findall(r"^\s*-\s+`([^`]+)`", out_m.group(1), re.MULTILINE)
    if len(out_paths) != 1:
        raise GeneratorError("Output must list exactly one output path")
    output_path = out_paths[0]

    src_block_m = re.search(r"##\s+Sources\s*\n(.*)$", body, re.DOTALL)
    if not src_block_m:
        raise GeneratorError("sources.md missing '## Sources' section")

    sources = []
    for sm in re.finditer(r"###\s+(.+?)\n(.*?)(?=\n###\s|\Z)", src_block_m.group(1), re.DOTALL):
        rel = sm.group(1).strip()
        chunk = sm.group(2)
        reason_m = re.search(r"Reason:\s*(.+)", chunk)
        if not reason_m or not reason_m.group(1).strip():
            raise GeneratorError(f"source {rel!r} missing a non-empty 'Reason:'")
        sections = re.findall(r"^\s*-\s+(.+?)\s*$", chunk.split("Sections:", 1)[-1], re.MULTILINE) \
            if "Sections:" in chunk else []
        sections = [s for s in sections if s]
        if not sections:
            raise GeneratorError(f"source {rel!r} lists no explicit Sections")
        sources.append({"path": rel, "reason": reason_m.group(1).strip(), "sections": sections})
    if not sources:
        raise GeneratorError("sources.md lists no sources")
    return output_path, sources


def extract_section(doc: str, heading: str) -> str:
    """Return a named heading's block: the heading line + body up to the next heading of equal/higher
    level. Raises if the heading is absent or its body is empty. Never falls back to the whole file."""
    lines = doc.splitlines()
    start = None
    level = None
    for i, line in enumerate(lines):
        hm = re.match(r"^(#+)\s+(.*)$", line)
        if hm and hm.group(2).strip() == heading:
            start = i
            level = len(hm.group(1))
            break
    if start is None:
        raise GeneratorError(f"section not found: {heading!r}")
    body = []
    for line in lines[start + 1:]:
        hm = re.match(r"^(#+)\s+", line)
        if hm and len(hm.group(1)) <= level:
            break
        body.append(line)
    text = "\n".join(body).strip()
    if not text:
        raise GeneratorError(f"section is empty: {heading!r}")
    return text


def render(sources: list[dict]) -> str:
    """Deterministic assembly of the self-knowledge document."""
    parts = [
        "---",
        "minimum_authority: admin",
        "status: active",
        "---",
        "",
        GENERATED_NOTICE,
        "",
        "# James — Self-Knowledge",
        "",
        DISCLOSURE_POLICY,
        "",
        "## Summary",
        "",
        REVIEWED_SUMMARY,
        "",
    ]
    for src in sources:
        path = _validate_source_path(src["path"])
        doc = path.read_text(encoding="utf-8")
        for heading in src["sections"]:
            extract = extract_section(doc, heading)
            _scan_secrets(extract, f"{src['path']} § {heading}")
            parts += [f"## {heading}", "", f"_Source: `{src['path']}`_", "", extract, ""]
    output = "\n".join(parts).rstrip() + "\n"
    _scan_secrets(output, "generated output")
    return output


def build() -> tuple[Path, str]:
    if not SOURCES_FILE.exists():
        raise GeneratorError(f"missing source list: {SOURCES_FILE}")
    output_rel, sources = parse_sources(SOURCES_FILE.read_text(encoding="utf-8"))
    if ".." in output_rel.split("/") or output_rel.startswith("/"):
        raise GeneratorError(f"unsafe output path: {output_rel!r}")
    return (REPO_ROOT / output_rel), render(sources)


def cmd_generate() -> int:
    out_path, content = build()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    print(f"generated {out_path.relative_to(REPO_ROOT)} ({len(content)} bytes)")
    return 0


def cmd_check() -> int:
    out_path, content = build()
    if not out_path.exists():
        print(f"MISSING: {out_path.relative_to(REPO_ROOT)} — run: generate", file=sys.stderr)
        return 1
    if out_path.read_text(encoding="utf-8") != content:
        print(f"STALE: {out_path.relative_to(REPO_ROOT)} differs — run: generate", file=sys.stderr)
        return 1
    print(f"self-knowledge OK ({out_path.relative_to(REPO_ROOT)})")
    return 0


def main(argv: list[str]) -> int:
    if len(argv) != 2 or argv[1] not in ("generate", "check"):
        print("usage: build_agent_self_knowledge.py {generate|check}", file=sys.stderr)
        return 2
    try:
        return cmd_generate() if argv[1] == "generate" else cmd_check()
    except GeneratorError as e:
        print(f"error: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
