#!/usr/bin/env python3
"""Sync tracked story-summary files from the full story files (story-37).

Full stories live in `product/stories/` (active) and `product/stories/archive/` (done/
rejected/superseded/abandoned). The tracked compact summaries are the product surface:

  product/stories-list.md       — curated forward-looking backlog (HAND-CURATED; validated, not
                                   overwritten, because it lists planned stories with no full file yet)
  product/stories-archive.md    — GENERATED from product/stories/archive/
  product/stories-parkinglot.md — parked/deferred (hand-maintained)
  product/stories-proposals.md  — governed agent proposals (proposal<N>)

Usage:
  python3 scripts/sync_story_summaries.py generate   # rewrite the generated block of stories-archive.md
  python3 scripts/sync_story_summaries.py check       # validate; exit non-zero on problems (CI)
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STORIES = ROOT / "product" / "stories"
ARCHIVE = STORIES / "archive"
ARCHIVE_MD = ROOT / "product" / "stories-archive.md"

GEN_START = "<!-- BEGIN generated: archived stories -->"
GEN_END = "<!-- END generated -->"


def _num_sort_key(num: str) -> tuple:
    m = re.match(r"(\d+)", num)
    return (int(m.group(1)) if m else 9999, num)


def parse_story(path: Path) -> dict:
    text = path.read_text()
    m = re.match(r"story-(\d+[a-z]?)-", path.name)
    num = m.group(1) if m else "?"
    title = next((ln[2:].strip() for ln in text.splitlines() if ln.startswith("# ")), path.stem)
    status = "?"
    lines = text.splitlines()
    for i, ln in enumerate(lines):
        if ln.strip().lower().startswith("## status"):
            for j in range(i + 1, min(i + 4, len(lines))):
                bm = re.search(r"\*\*(.+?)\*\*", lines[j])
                if bm:
                    status = bm.group(1)
                    break
            break
    if len(status) > 48:
        status = status[:45].rstrip() + "…"
    return {"num": num, "title": title, "status": status, "file": path.name}


def list_stories(directory: Path) -> list:
    if not directory.exists():
        return []
    return sorted((parse_story(p) for p in directory.glob("story-*.md")),
                  key=lambda s: _num_sort_key(s["num"]))


def _archive_block() -> str:
    rows = [f"| {s['num']} | {s['title']} | {s['status']} | `{s['file']}` |"
            for s in list_stories(ARCHIVE)]
    table = "| # | Title | Outcome | File |\n|----|----|----|----|\n" + (
        "\n".join(rows) if rows else "| — | _(none yet)_ | | |")
    return f"{GEN_START}\n{table}\n{GEN_END}"


def generate() -> None:
    header = (
        "# Stories — Archive\n\n"
        "Completed / rejected / superseded / abandoned stories. The block below is generated by "
        "`scripts/sync_story_summaries.py generate` from `product/stories/archive/` — do not hand-edit it.\n\n"
    )
    ARCHIVE_MD.write_text(header + _archive_block() + "\n")
    print(f"generated {ARCHIVE_MD.relative_to(ROOT)} ({len(list_stories(ARCHIVE))} archived)")


def _check() -> list:
    """Return a list of problem strings (empty = OK). Pure/testable."""
    problems = []
    active = list_stories(STORIES)
    archived = list_stories(ARCHIVE)
    seen = {}
    for s in active + archived:
        seen.setdefault(s["num"], []).append(s["file"])
    for num, files in sorted(seen.items(), key=lambda kv: _num_sort_key(kv[0])):
        if len(files) > 1:
            problems.append(f"duplicate story number {num}: {files}")
    if not ARCHIVE_MD.exists():
        problems.append("product/stories-archive.md missing — run: generate")
    elif _archive_block() not in ARCHIVE_MD.read_text():
        problems.append("product/stories-archive.md generated block is stale — run: generate")
    return problems


def check() -> None:
    problems = _check()
    if problems:
        print("STORY SUMMARY CHECK FAILED:")
        for p in problems:
            print("  -", p)
        sys.exit(1)
    print(f"story summaries OK ({len(list_stories(STORIES))} active, {len(list_stories(ARCHIVE))} archived)")


def main() -> None:
    cmd = sys.argv[1] if len(sys.argv) > 1 else "check"
    if cmd == "generate":
        generate()
    elif cmd == "check":
        check()
    else:
        print("usage: sync_story_summaries.py [generate|check]")
        sys.exit(2)


if __name__ == "__main__":
    main()
